esfiddle/esfiddle

- Gruntfile.js
- package.json
PR for the issue " Add image optimisation task to grunt" (#4 in open issues). Added grunt-contrib-imagemin to package.json and gruntfile, to minify any jpg, png or gif. Please have a look and suggest if anything is missing.
Note: First PR to open source project.
> Added grunt-contrib-imagemin to minify images.

- Gruntfile.js
- src/redirect_traffic.js
PR for the issue "Automatically redirect http traffic to https" (#7 in open issues).  Created a new javascript file in src directory and added it in Gruntfile. Please have a look and suggest if anything is missing.
> Redirect traffic to HTTPS from HTTP if not done automatically

- .gitignore
- README.md
- REPORTBUG.md
> fix #1 Update README.md 

- CODE_OF_CONDUCT.md
> added email address

- .eslintrc
> fixes issue #70

- src/examples/arrow-example.js
- src/examples/block-scope-example.js
- src/examples/class-example.js
- src/examples/default-param-example.js
- src/examples/destructure-example.js
- src/examples/es7-array-includes-example.js
- src/examples/es7-eponentiation-operator-example.js
- src/examples/es7-includes-index-example.js
- src/examples/generator-example.js
- src/examples/iterator-example.js
- src/examples/map-example.js
- src/examples/promise-example.js
- src/examples/rest-example.js
- src/examples/set-example.js
- src/examples/spread-example.js
- src/examples/template-example.js
Changed examples from using string arrays to template literals for better readable code.
> Use template literals in examples

- src/examples/internationalization-localization.js
Added an example for ES6 Internationalization and Localization features
> Adding example for ES6 Internationalization and Localization features

- src/js/examples/promise-example.js
> improve example code for promises - part of #74

- src/js/index.js
Per the Code Mirror documentation, the language mode should be included. I've gone ahead and added an import statement to ensure it's a part of the bundle.
> Import javascript mode for CM syntax highlighting

- README.md
- docs/HOW_TO_INSTALL_NODEJS_AND_MONGODB.md
- [x ] Your pull request targets the `develop` branch.
- [ x] New feature (non-breaking change which adds new functionality)
- [x ] Tested changes locally.
Updated README.md to link to HOW_TO_INSTALL_NODEJS_AND_MONGODB.md
Created HOW_TO_INSTALL_NODEJS_AND_MONGODB.md, which is aimed to help new users get their workstation setup.
> Added instructions on how to install NodeJS and MongoDB

- views/blog/header.ejs
I have this error when performing the test: 
```Failed at the es6-fiddle-web@1.0.0 test-node script 'mocha test/*.test.js'.```
I have no idea, and new to node & js. Anyone can help?
Change the favicon for the blog.
Thanks in advance for all the help.
> Change the favicon for the blog #118

- Gruntfile.js
- dist/about.html
- dist/style/about.css
- src/views/about.html
- style/about.less
- style/pages/about.less
This PR is meant to give About page the proper styling it needs to be consistent with the rest of the site. This includes changes to the navbar, margins, padding, etc. 
The following changes are made:
- Created about.less file to use existing style components (consistency)
- Linked stylesheet in head of about.html
- Added about.less to Gruntfile.js
- Made a few grammatical/punctuation corrections
I just want to note that, for issue #114, @joshghent also pointed out a footer problem but I noticed only the blog page has a footer. If that's the case, I can create a separate issue and work on it. Let me know!
> Issue #114 Fixed: Update about page styling to be consistent with rest of site

- docs/FAQ.md
- [✅] Your pull request targets the `develop` branch.
- [✅] Branch starts with either `fix/` or `feature/`
- [✅] All new and existing tests pass the command `npm test`.
- [❌] Any new files are included in the grunt tasks
- [     ] Small bug fix (non-breaking change which fixes an issue)
- [✅] New feature (non-breaking change which adds new functionality)
- [     ] Breaking change (fix or feature that would change existing functionality)
- [✅] Tested changes locally.
- [❌] New tests added?
- [❌] Closes currently open issue (replace XXXX with an issue no): Closes #XXXX
Added a basic FAQ file with most common questions.
After review and with community updates, a link to this file could be added to the main README.md file.
> Added basic FAQ

- docs/CONTRIBUTE.md
> fixed two spelling typos in the CONTRIBUTE.md file

- docs/CONTRIBUTORS.md
- package-lock.json
- server/app.js
- [?] Any new files are included in the grunt tasks
(How should I handle the package-lock.json file?)
(Used ngrok to ensure that Pagespeed did not raise issues)
- [N/A] New tests added?
I added additional logic to ensure that urls matching either /^\/(src\/es6-fiddle|src\/authenticated).+/ or /^\/(authenticated)/ are cached by the browser.
Also, I installed with npm v5, creating a package-lock.json.  I don't know of any issue with committing this, but give me a heads up if it should be removed.
> Feature 112

- views/profile/starredFiddles.ejs
> Fixed misspelled Starred Fiddles

- README.md
> added npm install to readme

- .gitignore
- src/js/examples/es7-includes-index-example.js
- src/js/examples/map-example.js
Add in missing semi-colons in ES6 map-example
Replace empty index with undefined in ES7 array includes: search from index
> [Bug fix] Fixes linting errors in default examples

- package.json
I added the engine property to package.json to check for Node versions "^6.11.1 || ^7.10.1 || >=8.1.4" (6, 7, and latest) to comply with the [July 2017, Node security release ](https://nodejs.org/en/blog/vulnerability/july-2017-security-releases/).
> Add node engine version check for security release #148

- README.md
There's a failed test unrelated to my README.md change.
This is the suggestion for #165. I changed `mv sample.env .env ` to `cp sample.env ./.env` in README.md.
> Update README to cp instead of mv sample.env

- Gruntfile.js
- src/js/frameBridge.js
- src/js/index.js
- src/js/layoutFunctions.js
- src/js/sandbox/iframe.js
- src/js/sandbox/keys.js
- src/js/sandbox/microevent.js
- src/views/iframe.html
- src/views/index.html
This PR adds the ability to run (un-trusted) user code in a sandbox created using [IFrame Sandbox](https://developer.mozilla.org/en/docs/Web/HTML/Element/iframe) and thus reduces the ability of the script can do.  
A live demo of the vulnerability can be [found here](https://esfiddle.net/j7075ohn/).
> Fix #171 (Stored XSS Vulnerability)

- docs/HOW_TO_INSTALL_NODEJS_AND_MONGODB.md
This PR improves solely the HOW_TO_INSTALL_NODEJS_AND_MONGODB doc. It improves some grammatical issues and fixes some typos.
> Fixed a typo and some grammar in docs.

- docs/CONTRIBUTE.md
Added information on what node versions we support into the contributors guide.
> Added node version recommendations to contributors guide. Closes #170.

- style/partials/media-queries.less
- views/blog/header.ejs
Changed the font size on the blog page when in low width mode.
> Fixed font-size not altering for blog page.

- package.json
- server/app.js
Integrated helmet in app.js.
***
please comment on improvements needed since this is first time contribution.
> closes #183

- style/partials/media-queries.less
fixed issue regarding setting popup not shown in mobile. please comment issue because overflow:scroll property is removed as I see no need for that
> closes issue #142 regarding settings popup

- src/js/add-examples.js
- src/js/es-editions.js
- src/js/examples/es8-async-await.js
- src/js/examples/es8-object-entries-values.js
- src/js/examples/es8-string-pad-start-end.js
- src/js/index.js
- src/views/index.html
Added examples for ES8
- `Object.entries` and `Object.values`
- `padStart` and `padEnd`
-  `async` and `await`
Refactored the example selector on-change to read from the new ECMAScript Editions file.
Also refactored addExamples to also leverage the ECMAScript Editions file.
> Added ES8 examples - Issue #177

- package-lock.json
- package.json
- src/js/sandbox/microevent.js
- [x ] Your pull request targets the `develop` branch.
- [ x] Branch starts with either `fix/` or `feature/`
- [x ] All new and existing tests pass the command `npm test`.
- [x ] Any new files are included in the grunt tasks
- [x ] Small bug fix (non-breaking change which fixes an issue)
- [x ] Tested changes locally.
- [x ] New tests added?
- [ x] Closes currently open issue (replace XXXX with an issue no): Closes #XXXX
Closes issue #199 
Node module babel-polyfill is required
Async and await runtime error was caused by babel-polyfill not running.
Babel-polyfill is required for regenerator to be defined.
> Fix Async and Await issue

- package-lock.json
- package.json
> Greenkeeper/mongoose 5.3.1

- src/js/clickEvents.js
Fixes the issue where the user couldn't toggle back to "light mode" by returning the `fiddle` theme back to `default`
> fix/ Fix issue where user couldn't toggle back to light mode

- src/index.css
My suggestion goes to change the focus ring color to one of the already existing colors in the projects' palette. Since involves a personal choice feel free to pick a different tone, I mostly wanted to show you can include a noticeable focus ring without compromising the website's main colors
> fix/ Change outline color

- src/js/clickEvents.js
> Fix issue #246

- src/js/clickEvents.js
> Fixed issue #248

- .gitignore
- package-lock.json
- package.json
- src/App.css
- src/App.tsx
- src/components/Editor/Editor.tsx
- src/components/Footer/Footer.css
- src/index.css
> Feat code editor
